name: Bunk_o_Meter
description: "Know how many you can skip!"
publish_to: 'Ujwal Kumar S'

version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  shared_preferences: ^2.2.2

  material_color_utilities: 0.11.1
  flutter:
    sdk: flutter
  ffi: ^2.0.2  # Required for C++ integration
  cupertino_icons: ^1.0.8
  intl: ^0.20.2  # Or latest version
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # This should be inside dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/bunk_o_meter_Logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/bunk_o_meter_Logo.png"
